name: tests

on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        cache: true
    - run: go version

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./main.go

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Install vulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run vulncheck
      run: govulncheck ./...

    - name: Run go tests
      run: go test -race -vet=off ./...

    - name: Run e2e tests
      run: |-
        rm -rf ./tests/output/*
        ./tests/run.bash
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "tests differ"
          git diff
          exit 1
        fi
